#!/bin/bash

export OPENLANE_ROOT=$(pwd)/dependencies/openlane_src
export OPENLANE_PDK=$(pwd)/dependencies/pdks
export PDK_ROOT=$(pwd)/dependencies/pdks
# export PDK sky130A
export PDK=gf180mcuC

# source ./openlane-env/bin/activate

